# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{devise_zotable}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alberto Zuin"]
  s.date = %q{2013-02-05}
  s.description = %q{For using Massimo's authentication system}
  s.email = %q{alberto@azns.it}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
     "README.md",
     "Rakefile",
     "VERSION",
     "devise_zotable.gemspec",
     "lib/devise_zotable.rb",
     "lib/devise_zotable/zot_adapter.rb",
     "lib/devise_zotable/model.rb",
     "lib/devise_zotable/schema.rb",
     "lib/devise_zotable/strategy.rb",
     "rails/init.rb",
     "test/devise_zotable_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://62.77.32.240:6380/alzuin/devise_zotable}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Devise Zotsell authentication module}
  s.test_files = [
    "test/devise_zotable_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<devise>, ["> 1.0.4"])
    else
      s.add_dependency(%q<devise>, ["> 1.0.4"])
    end
  else
    s.add_dependency(%q<devise>, ["> 1.0.4"])
  end
end

